previewsEnabled: true
services:
  - name: race-website
    type: web
    env: node
    region: frankfurt
    rootDir: race-website
    buildCommand: npm install && npm run build
    buildFilter:
      paths:
        - race-website/src/**/*
        - race-website/static/**/*
    startCommand: node build/index.js
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: STRAPI_API_TOKEN
        sync: false
      - key: STRAPI_URL
        fromService:
          name: race-admin
          type: web
          envVarKey: RENDER_EXTERNAL_URL
  - name: race-admin
    type: web
    env: node
    rootDir: race-admin
    plan: starter
    region: frankfurt
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    buildFilter:
      paths:
      - race-admin/config/**/*
      - race-admin/src/**/*
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: strapi
    plan: starter
    region: frankfurt
