name: 'Test Preview Environment'

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: 'Get Preview Environment URL'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      env_status: ${{ steps.wait.outputs.env_status }}
      env_url: ${{ steps.wait.outputs.env_url }}  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - uses: actions/checkout@v2
      - uses: pascalvaccaro/check-render-preview@v1.0.2
        id: admin
        with:
          SERVICE_NAME: race-admin
      - uses: pascalvaccaro/check-render-preview@v1.0.2
        if: ${{ steps.admin.outputs.env_status == 'success' }}
        id: wait
        with:
          SERVICE_NAME: race-website
  e2e:
    name: 'Run end-to-end test suite with Cypress'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: check
    if: needs.check.outputs.env_status == 'success'
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run Cypress suite
        run: npm run e2e:run
        env:
          CYPRESS_API_URL: https://director-x2il.onrender.com
          FRONTEND_URL: ${{ needs.check.outputs.env_url }}
